name: Prod Deploy Template

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get previous release tag
        id: prev-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PREV_RELEASE=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "::set-output name=tag::$PREV_RELEASE"
      - name: Generate release notes
        id: release-notes
        run: |
          PREV_TAG=${{ steps.prev-release.outputs.tag }}
          NEW_TAG=${{ inputs.tag }}
          NOTES=$(git log $PREV_TAG..$NEW_TAG --oneline)
          echo "Release notes:"
          echo "$NOTES"
          echo "notes=$NOTES" >> "$GITHUB_OUTPUT"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ inputs.tag }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ inputs.tag }}" \
              --notes="${{ steps.release-notes.outputs.notes }}"
      - run: echo "Deploying my_image:${{ inputs.tag }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."